#pragma once

#include <easy_pc/easy_pc.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct TypeDescriptor TypeDescriptor;
typedef struct symbol symbol_t;

typedef struct odin_grammar_node_t odin_grammar_node_t;

typedef enum
{
    AST_NODE_PROGRAM,
    AST_NODE_EXTERNAL_DECLARATIONS,
    AST_NODE_PACKAGE_CLAUSE,
    AST_NODE_IMPORT,
    AST_NODE_IMPORT_NAMED,
    AST_NODE_IDENTIFIER,
    AST_NODE_POLY_IDENT,
    AST_NODE_BASIC_TYPE,
    AST_NODE_POINTER_TYPE,
    AST_NODE_ARRAY_TYPE,
    AST_NODE_DYNAMIC_ARRAY_TYPE,
    AST_NODE_SLICE_TYPE,
    AST_NODE_MAP_TYPE,
    AST_NODE_SOA_TYPE,
    AST_NODE_ENUM_TYPE,
    AST_NODE_ENUM_TYPE_REF,
    AST_NODE_UNION_TYPE,
    AST_NODE_BIT_FIELD_TYPE,
    AST_NODE_BIT_SET_TYPE,
    AST_NODE_STRUCT_TYPE,
    AST_NODE_STRUCT_TYPE_REF,
    AST_NODE_TYPE_NAME,
    AST_NODE_DISTINCT_TYPE,
    AST_NODE_PROCEDURE_SIGNATURE,
    AST_NODE_PARAMETER,
    AST_NODE_PARAMETERS,
    AST_NODE_PARAMETER_LIST,
    AST_NODE_NAMED_RETURN,
    AST_NODE_RETURN_LIST,
    AST_NODE_RETURNS,
    AST_NODE_WHERE_CLAUSE,
    AST_NODE_PRIMARY_EXPRESSION,
    AST_NODE_POSTFIX_CALL,
    AST_NODE_POSTFIX_SUBSCRIPT,
    AST_NODE_POSTFIX_SLICE,
    AST_NODE_POSTFIX_SLICE_LT,
    AST_NODE_POSTFIX_MEMBER,
    AST_NODE_POSTFIX_DEREF,
    AST_NODE_POSTFIX_ASSERTION,
    AST_NODE_POSTFIX_OPS,
    AST_NODE_POSTFIX_EXPRESSION,
    AST_NODE_UNARY_OP,
    AST_NODE_UNARY_EXPRESSION,
    AST_NODE_MUL_OP,
    AST_NODE_MUL_EXPRESSION,
    AST_NODE_ADD_OP,
    AST_NODE_ADD_EXPRESSION,
    AST_NODE_SHIFT_OP,
    AST_NODE_SHIFT_EXPRESSION,
    AST_NODE_BIT_AND_OP,
    AST_NODE_BIT_AND_EXPRESSION,
    AST_NODE_BIT_XOR_OP,
    AST_NODE_BIT_XOR_EXPRESSION,
    AST_NODE_BIT_OR_OP,
    AST_NODE_BIT_OR_EXPRESSION,
    AST_NODE_COMP_OP,
    AST_NODE_COMP_EXPRESSION,
    AST_NODE_LOG_AND_OP,
    AST_NODE_LOG_AND_EXPRESSION,
    AST_NODE_LOG_OR_OP,
    AST_NODE_LOG_OR_EXPRESSION,
    AST_NODE_RANGE_OP,
    AST_NODE_RANGE_EXPRESSION,
    AST_NODE_TERNARY_EXPRESSION,
    AST_NODE_OR_ELSE,
    AST_NODE_OR_RETURN,
    AST_NODE_ASSIGN_OP,
    AST_NODE_ASSIGN_EXPRESSION,
    AST_NODE_EXPRESSION,
    AST_NODE_ARGUMENT_LIST,
    AST_NODE_COMPOUND_STATEMENT,
    AST_NODE_DEFER_STATEMENT,
    AST_NODE_WHEN_STATEMENT,
    AST_NODE_IF_STATEMENT,
    AST_NODE_FOR_STATEMENT,
    AST_NODE_SWITCH_STATEMENT,
    AST_NODE_SWITCH_CASE,
    AST_NODE_SWITCH_DEFAULT,
    AST_NODE_RETURN_STATEMENT,
    AST_NODE_BREAK_STATEMENT,
    AST_NODE_CONTINUE_STATEMENT,
    AST_NODE_FALLTHROUGH_STATEMENT,
    AST_NODE_ASSIGN_STATEMENT,
    AST_NODE_EXPRESSION_STATEMENT,
    AST_NODE_PROCEDURE_LITERAL,
    AST_NODE_VARIABLE_DECL,
    AST_NODE_CONSTANT_DECL,
    AST_NODE_FOREIGN_IMPORT,
    AST_NODE_FOREIGN_BLOCK,
    AST_NODE_WHEN_DECL,
    AST_NODE_USING_DECL,
    AST_NODE_TOP_LEVEL_DECLARATION,
    AST_NODE_DIRECTIVE,
    AST_NODE_DIRECTIVE_WITH_ARGS,
    AST_NODE_INTEGER_BASE,
    AST_NODE_INTEGER_VALUE,
    AST_NODE_FLOAT_BASE,
    AST_NODE_FLOAT_VALUE,
    AST_NODE_STRING_LITERAL,
    AST_NODE_RAW_STRING_LITERAL,
    AST_NODE_RUNE_LITERAL,
    AST_NODE_BOOL_TRUE,
    AST_NODE_BOOL_FALSE,
    AST_NODE_NIL,
    AST_NODE_NONE,
    AST_NODE_ELLIPSIS,
    AST_NODE_ENUMERATOR,
    AST_NODE_ENUMERATOR_LIST,
    AST_NODE_UNION_FIELD,
    AST_NODE_UNION_FIELD_LIST,
    AST_NODE_BIT_FIELD_FIELD,
    AST_NODE_BIT_FIELD_FIELD_LIST,
    AST_NODE_STRUCT_FIELD,
    AST_NODE_STRUCT_FIELD_LIST,
} odin_grammar_node_type_t;

typedef struct
{
    odin_grammar_node_t ** children;
    size_t count;
} ast_node_list_t;

typedef struct
{
    epc_parser_input_view_t view;
} input_source_data_t;

typedef struct odin_grammar_node_t
{
    odin_grammar_node_type_t type;
    input_source_data_t source_data;

    ast_node_list_t list;

    char const * text;

    // Semantic analysis annotations
    TypeDescriptor * resolved_type;
    symbol_t * resolved_symbol;

    union
    {
        ast_node_list_t external_declarations;
    };
} odin_grammar_node_t;

void odin_grammar_node_free(void * node, void * user_data);
