#pragma once

typedef enum
{
    TYPE_KIND_BASIC,
    TYPE_KIND_POINTER,
    TYPE_KIND_ARRAY,
    TYPE_KIND_SLICE,
    TYPE_KIND_DYNAMIC_ARRAY,
    TYPE_KIND_STRUCT,
    TYPE_KIND_UNION,
    TYPE_KIND_ENUM,
    TYPE_KIND_BIT_FIELD,
    TYPE_KIND_BIT_SET,
    TYPE_KIND_MAP,
    TYPE_KIND_PROC,
    TYPE_KIND_DISTINCT,
    TYPE_KIND_SOA,
    TYPE_KIND_COUNT__,
} type_kind_t;
